name: publish

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  TAG_NAME: beehive:${{ github.sha }}
  BUILD_VERSION: ${{ github.sha }}
  GITHUB_IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/beehive
  GITHUB_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/beehive:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the tag or commit id
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_OR_COMMIT=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            echo "This is a tag: $TAG_OR_COMMIT"
          else
            TAG_OR_COMMIT=$(echo $GITHUB_SHA)
            echo "This is a commit SHA: $TAG_OR_COMMIT"
          fi
          echo "TAG_OR_COMMIT=$TAG_OR_COMMIT" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.GITHUB_IMAGE_NAME }}
          build-args: |
            BUILD_VERSION=${{ steps.version.outputs.TAG_OR_COMMIT }}
          cache-from: |
            type=gha
            type=registry,ref=${{ env.GITHUB_IMAGE_REPO }}:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ env.GITHUB_IMAGE_REPO }}:buildcache,mode=max
          platforms: linux/amd64
